### ISSUE TITLE
Process names with spaces not correctly recognized by system.lua

### ISSUE THREAD

**Issue by M4he** [worron/redflat#12]
## Preface

Firefox is spawning a process called "`Web Content`". The output of `/proc/<pid>/stat` will be

    <pid> (Web Content) S 11111 9175 9175 ...

Notice the space in the process name of the second field.

## Issue

The [regex used for splitting the `proc` output](https://github.com/worron/redflat/blob/f6f6f97259409645ddee661fd62cdf5623a20039/system.lua#L498) is not compatible with process names that have spaces in them. This leads to:

- the name field is getting cut to just `(Web`
    - the [regex for process the name](https://github.com/worron/redflat/blob/f6f6f97259409645ddee661fd62cdf5623a20039/system.lua#L503) will not trigger anymore, resulting in the `name` being set to `nil`
- since the name is essentially split into two separate fields within the first regex (`(Web` and `Content)`) all elements in the table are shifted by 1
    - thus, the [memory usage parse line](https://github.com/worron/redflat/blob/f6f6f97259409645ddee661fd62cdf5623a20039/system.lua#L508) will grab the wrong value
- finally, there's an item in the result list that has:
    - `name = nil`
    - `mem = <huge_number>`

The item with no name an huge memory usage value will always be the first item in the memory listing due to `top`'s `sort_by_mem()`. Since the name is `nil`, the name of the previous process [is kept](https://github.com/worron/redflat/blob/f6f6f97259409645ddee661fd62cdf5623a20039/float/top.lua#L155) but is now assigned a completely wrong memory usage:

![top_bug](https://user-images.githubusercontent.com/1408105/32220311-8dd1d326-be31-11e7-9055-2536079024aa.png)

Also I suspect the PID is still updated, so the "kill" button would actually kill the wrong process as well.

## Proposed Fix

I presume the fix would be following:

- adjust the [regex used for splitting the `proc` output](https://github.com/worron/redflat/blob/f6f6f97259409645ddee661fd62cdf5623a20039/system.lua#L498) to treat strings within brackets as a single entity, not splitting them at whitespaces
- adjust the [regex for process the name](https://github.com/worron/redflat/blob/f6f6f97259409645ddee661fd62cdf5623a20039/system.lua#L503) to grab the whole string within the brackets, even with whitespaces

I'm not good at regex, sadly. I could look into it but maybe you can come up with a solution way quicker? :)

**Comment by worron** [comment]
Thanks for detailed report. Unfortunately I can't reproduce this bug right now, seems it depends on Firefox version. Hope you can test this patch and report how it works.

**Comment by M4he** [comment]
Seems to work beautifully. As always, thanks for the quick fix!
