### ISSUE TITLE
Input blocked

### ISSUE THREAD

**Issue by VPeruS** [worron/redflat#2]
When use combination for application switch, it pop-up, get keyboard focus and that`s all only killing wm solve problem. Same happens with app quick launcher.

**Comment by worron** [comment]
I would like to check some details first.

Was any additional modification (CapsLock, NumLock, etc.) active?
Does the problem appear with English or non-English keyboard layout?

**Comment by VPeruS** [comment]
NumLock was On, everything else - off, English layout. Disabling NumLock solved problem with switcher but launcher still block input.

**Comment by worron** [comment]
Unfortunately I can't reproduce problem with launcher.

Does any letter appear in launcher text field when you printing?
Does prompt box widget (`Mod4+p`) work?

**Comment by VPeruS** [comment]
Mod4+p work very well.
Here is screenshoot what happens when i press mod4+f3
![2017-04-22-022657_1366x768_scrot](https://cloud.githubusercontent.com/assets/7927055/25298941/d43d19f4-2702-11e7-877c-644431406ba6.png)

**Comment by worron** [comment]
Ok, thanks for screenshot, seems it was misunderstanding and I mixed up app launcher widget (`Mod4+r`) and quick launch widget (`Mod4+F3`).

Still can't figure the problem.
Does widget show any reaction on number keys, 'Escape' and 'Enter' keys?
Can you provide awesomewm error log?

**Comment by VPeruS** [comment]
I didn't tested Esc in case with disabled NumLock, my bad. Everything works fine with disabled modifiers.
