### ISSUE TITLE
Task tooltip UX behavior for single clients

### ISSUE THREAD

**Issue by M4he** [worron/redflat#23]
After using redflat for quite some time now and growing accustomed to its UI behavior, one thing started to bug me a bit: the `tasklist` tooltip has no button functions for single clients (non-grouped tasks).

The code in question: https://github.com/worron/redflat/blob/62616b006e6b36863ff7f078c5d9b8b3e25db3e2/widget/tasklist.lua#L422

Seeing the conditional and the comment in the code, it's obvious you intentionally made it this way. That's why I refrained from simply changing this and putting up a PR. Instead I'd like to present my opinion on this, so maybe we can discuss the pros and cons of this.

From a UX point of view, the tooltip entries' behavior on grouped tasks suggest they can be left- and right-clicked to access the window-specific function such as raise or menu. Visually the tooltips for single (non-grouped) clients are identical to grouped ones but their behavior is not: they don't respond to clicks. Sure the `tasklist` button itself provides those functions instead for single clients, thus it isn't strictly required for the tooltip to do the same again.

However, from a UX point of view, visually and contextually identical elements should behave the same if possible, in my opinion. I often find myself erronously clicking a single client's tooltip just to be reminded I have to use the `tasklist` button in this special case instead because it is a single client.

I currently see no downside of using the full functionality (highlight, click actions) of tooltips for single clients as well. Am I overlooking something here? What's your opinion on this?

**Comment by worron** [comment]
>Visually the tooltips for single (non-grouped) clients are identical to grouped ones

That's not entirely true. Single ones have no state highlights. I really don't like colorization for single line tooltip just in terms of look and feel. Something triggered in my mind and I decide to remove buttons actions as well.

I think there is no harm by enabling buttons (but not highlights) for single app tooltip. Except some "behaviour inconsistent" when you have color feedback on click for multi-line tooltip but not for single-line.

And the second solution will be adding new variable to theme  by which single-line tooltip behaviour and appearance will be determinated by user. Just used to make customizable everything what is questionable.

What do you think about this variants?

**Comment by M4he** [comment]
Thanks for your consideration and feedback on this! I think the crucial feature here are mainly the buttons actions. So if I understand correctly, we could agree on adding them back for single clients in general?

Regarding the highlights, I would favor the customizability approach if it does not introduce any disadvantages.

**Comment by worron** [comment]
Ok, you can check it. No highlights by default, switch `style.tasktip.sl_highlight` to enable it.

**Comment by M4he** [comment]
Works beautifully, thank you!
