### ISSUE TITLE
Application launcher fails when program.Name is nil

### ISSUE THREAD

**Issue by lunamystry** [worron/redflat#28]
Hi,

The line: /home/leny/.config/awesome/redflat/service/dfparser.lua:233
fails if the program.Name is nil

On my computer, this seems to be cause by program.Exec==ibus-daemon

This seems to be the fix: https://github.com/awesomeWM/awesome/pull/83/files

**Comment by worron** [comment]
Ok, mentioned fix added, check how it works.

**Comment by lunamystry** [comment]
It works fine now! Thank you @worron
