### ISSUE TITLE
Minitray not drawing background

### ISSUE THREAD

**Issue by emhep** [worron/redflat#31]
The minitray widget is not drawing the background and border, the tray's icons still display and can be interacted with. If compton shadows are enabled the outline of the box can be seen in the correct location and in the correct shape. In addition, if icons like nm-applet update the icon, the new icon is drawn on top of the older icons for nm-applet. If there are no tray icons then the background is drawn and will continue to draw until the tray is closed even if tray icons are added.

I am running arch and am currently fully updated. This issue did not occur at first. I attempted to pull down a new copy of your example redflat configs only changing rc.lua so that the colorless config was the only one uncommented. This did not resolve the issue.

Additionally, this issue does not seem to affect other awesome drawn things such as the tooltips or the menu that appears when you right click on an item in the task list.

A pic showing the minitray outlined by compton shadows.
![minitray](https://user-images.githubusercontent.com/20485537/45791678-e37b2b00-bc47-11e8-9252-80f931e500e7.png)

**Comment by worron** [comment]
Unfortunately can't reproduce the problem. Minitray doesn't change `systray` mechanics, check how tray works with default awesomewm config.

Also [this thread](https://github.com/awesomeWM/awesome/issues/1720) can be useful.

**Comment by emhep** [comment]
This issue does affect the default config. There are also reports of i3 being affected.

The issue seems to be related to a recent GTK update as outlined in [this](https://gitlab.gnome.org/GNOME/gtk/issues/1280) issue report.

**Comment by worron** [comment]
>This issue does affect the default config

Not sure I can help here then.

>If there are no tray icons then the background is drawn and will continue to draw until the tray is closed even if tray icons are added

So does the background disappear after minitray reopened? If your applications autostarted, can you try to start it with few seconds delay after awesomewm?

**Comment by emhep** [comment]
The issue occurs even if I manually start the tray element after awesome starts. I am going to wait and see if the GTK bug gets resolved since I believe that that is the issue.
