### ISSUE TITLE
readme or documentation

### ISSUE THREAD

**Issue by paranoid73** [worron/redflat#47]
Hi , 
really nice work but possible to get a documentation for using your module ?

**Comment by worron** [comment]
I'm afraid it's unlikely possible in the nearest future. The module is hobby project and doesn't have stable API so far. I prefer not invest to documentation at this point. Config repo has plenty code as usage example and `colorless` theme file full of style hints. That's all for now.

Hope for your understanding.

**Comment by paranoid73** [comment]
it's ok . thank you
