### ISSUE TITLE
layout problem on the desktop

### ISSUE THREAD

**Issue by paranoid73** [worron/redflat#48]
my screen size : 1366x768
![Screenshot_2019-06-10_16-14-52](https://user-images.githubusercontent.com/34898251/59209548-16c96580-8b9b-11e9-87c7-463fa71f2cdc.png)

**Comment by worron** [comment]
This desktop configured for 1920x1080, you should fix widget placement and sizes for your resolution.
Start [from here](https://github.com/worron/awesome-config/blob/9454e7b42f54d00c145bce100eb47b84000ca494/themes/ruby/theme.lua#L40) changing right margin
```lua
edge = { width = { 100, 200 }, height = { 100, 100 } }
```
