### ISSUE TITLE
When moving wibar to the top the minitray widget keeps popped up from the bottom

### ISSUE THREAD

**Issue by iddm** [worron/redflat#5]
Moving `wibar` to the top in the `rc-blue.lua` does not set `minitray` widget to be spawned also from the top so it spawns from the bottom while the mouse is at the top :)

**Comment by worron** [comment]
Yes, it is. Most of floating widgets can use custom position function. I use one to fix tray in right bottom corner. Just fix theme file by removing this function and tray will follow mouse then.
```lua
theme.widget.minitray = {
	border_width = 0,
	geometry     = { height = 40 },
	screen_gap   = 2 * theme.useless_gap,
	color        = { wibox = theme.color.wibox, border = theme.color.wibox },
	set_position = function() -- remove this for position by mouse
		return { x = mouse.screen.workarea.x + mouse.screen.workarea.width,
		         y = mouse.screen.workarea.y + mouse.screen.workarea.height }
	end,
}
```

**Comment by iddm** [comment]
Nice point, thanks. However, don't you think it is better to spawn the `minitray` right under the mouse all the time? For example, if you click the tray icon widget the mouse is above it anyway, so the `minitray` widget will be spawned correctly all the time.

**Comment by worron** [comment]
>However, don't you think it is better to spawn the minitray right under the mouse all the time?

No, I don't. There is a possibility to show tray by hotkey just to check apps. Anyway I moved this function to theme (read like individual settings) for better flexibility.

**Comment by iddm** [comment]
Thanks!
