### ISSUE TITLE
Pulse widget does not update default sink when headset is connected

### ISSUE THREAD

**Issue by rakanalh** [worron/redflat#59]
When awesome loads the widgets including the `pulse` widget, the default `_sink` attribute is set. This means that whenever a different headset (a bluetooth one for example) is connected, the default sink does not change to the new default.

**Comment by worron** [comment]
I agree that lack of dynamical sink update is a flaw of current audio widget realization. But proposed change have two problem. First of all it will deny manual set sink (which can be set among widget arguments). Second is performance issue. Function `get_default_sink` execute some shell command in synchronous mode. Doesn't feel right to force it on every volume change on setup where headset changes extremely rare (like mine). Some compromise solution I see in making sink update optional by widget argument `update_sink`, something like
```diff
diff --git a/widget/pulse.lua b/widget/pulse.lua
index 404f364..5bb7914 100644
--- a/widget/pulse.lua
+++ b/widget/pulse.lua
@@ -65,7 +65,7 @@ end
 -----------------------------------------------------------------------------------------------------------------------
 function pulse:change_volume(args)
 	-- initialize vars
-	self._sink = get_default_sink({ type = self._type })
+	if self._update_sink then self._sink = get_default_sink({ type = self._type }) end
 	args = redutil.table.merge(change_volume_default_args, args or {})
 	local diff = args.down and -args.step or args.step
 
@@ -109,7 +109,7 @@ end
 -----------------------------------------------------------------------------------------------------------------------
 function pulse:mute(args)
 	args = args or {}
-	self._sink = get_default_sink({ type = self._type })
+	if self._update_sink then self._sink = get_default_sink({ type = self._type }) end
 	if not self._type or not self._sink then return end
 
 	local mute = redutil.read.output(string.format("pacmd dump | grep 'set-%s-mute %s'", self._type, self._sink))
@@ -171,6 +171,7 @@ function pulse.new(args, style)
 	widg._type = args.type or "sink"
 	widg._sink = args.sink
 	widg._style = style
+	widg._update_sink = args.update_sink
 
 	table.insert(pulse.widgets, widg)
 

```

Doesn't test it, may be some improvements will be needed.

**Comment by rakanalh** [comment]
I have solved the issue using your suggestion along with a udev rule. Need to clean things up and will update the PR.

But follow up to your suggestion, `widg._update_sink` would be set every time we create a new `pulse` instance. Is this new instance created once every "awesome restart" or is it created everytime i press the "increase/decrease/mute volume" buttons?

Edit: Answering my own question... the `pulse` instance is created once. So it would require a restart for `_update_sink` to get set.
