### ISSUE TITLE
Borderless maximized windows

### ISSUE THREAD

**Issue by akemrir** [worron/redflat#63]
hi

I've changed behaviour to hide/unhide border on keystroke, but I have problems with awesome restart.
I don't know where to change when awesome starts, to remove border from maximized windows.

Could you help me with that?

**Comment by worron** [comment]
>I don't know where to change when awesome starts, to remove border from maximized windows

Did you try [Awesome WM](https://awesomewm.org/doc/api/libraries/awful.rules.html) rules? Something like this:
```lua
{
    rule = { maximized = true },
    properties = { border_width = 0 }
},
```

**Comment by akemrir** [comment]
Thanks for help.

```
		{
			rule = { maximized = true },
			callback = function(c)
				c.border_width = 0
				c.height = c.screen.workarea.height - 2 * c.border_width
			end
		},
```

This worked :)

**Comment by akemrir** [comment]
By the way. Very nice theme for awesome. This is my variation.
![pic-full-200927-1641-49](https://user-images.githubusercontent.com/240986/94367655-6b6e5800-00e0-11eb-9304-d26a65b9e15e.png)
