### ISSUE TITLE
Initial key registered twice by keychain

### ISSUE THREAD

**Issue by M4he** [worron/redflat#71]
I'm currently wrapping up a major redesign and restructure work on my own config with the goal of making my personal redflat fork obsolete by either contributing the changes (as done recently) or migrating very specific adjustments into separate extensions.

I'm still carrying around one last hotfix that prevents me from dropping my redflat fork entirely:

```diff
--- a/float/keychain.lua
+++ b/float/keychain.lua
@@ -123,7 +123,7 @@ function keychain:init(style)
                if event == "press" then return false end
 
                -- dirty fix for first key release
-               if self.actkey == key and #mod == 0 then self.actkey = nil; return end
+               if self.actkey == key then self.actkey = nil; return end
 
                if awful.util.table.hasitem(self.service.close,    key) then self:hide()
                elseif awful.util.table.hasitem(self.service.stepback, key) then self:undo()
```

Essentially, when I don't use that adjustment as soon as I press the combination for the keychain - which is `[Alt] + [c]` for me (I use `Mod1` as mod key) - the key `[c]` is oftentimes registered a second time. That makes the keychain display `A-c c` instead of `A-c` and requires me to press backspace once in order to clear the second `[c]` which is otherwise interpreted as the first character for the keychain. I can reproduce this on two entirely different machines.

Judging from the comment above the affected line of code, it seems the `#mod == 0` check is there specifically for some key release handling. What was the reason behind this? I'm guessing that it behaves differently with `Mod4` or your specific setup?

**Comment by worron** [comment]
The `self.actkey == key` condition designed to prevent double registration for first key (since the widget activated by press, but `keychain` inner keygrabber configured for key releases). Because of it I don't met twice keys registration with `Mod4` neither `Mod1`. Extra `#mod == 0` is some artifact from early version of `keychain` I can't find any needs for it on current my setups. Seems safe to change whole condition:
```lua
if self.actkey == key then self.actkey = nil; return end
```
