### ISSUE TITLE
Grid layout multimonitor error popup message

### ISSUE THREAD

**Issue by M4he** [worron/redflat#9]
## Preface

I change my screen layout to use both my internal display (`eDP1`) as well as an external monitor (`HDMI1`). The latter is placed on top and is marked as primary. Awesome seems to restart itself automatically, as soon as the layout changes:

    xrandr --output HDMI1 --primary --auto;
    xrandr --output eDP1 --auto --below HDMI1;

- I've got a grid layout on the lower display (`eDP1`) but a tiling layout on the top one.
- the displays have different resolutions
    - eDP1: 1440x900
    - HDMI1: 1920x1080

## Issue

- I connect the external display and execute the `xrandr` commands as aboce
- I move a window from the top screen to the lower one via mouse dragging
- the window transitions from **Tile** mode to **Grid** mode
- an error message is displayed once:

      redflat/layout/grid.lua:203: attempt to index local 'cell' (a nil value)

## Possible Fix

The error message only happens _once_ when the first client enters the lower screen after connecting the external monitor. If I adjust the [`is_diff()` function](https://github.com/worron/redflat/blob/b81c0555edc44abf6503cf2db00447f7f10a3346/layout/grid.lua#L201) as portrayed below, the message doesn't appear:

    local function is_diff(g1, g2, cell)
        if not cell then return false end
        for k, v in pairs(g1) do
            if math.abs(g2[k] - v) >= cell[k] then return true end
        end

        return false
    end

(added `if not cell then return false end`)

The error does not appear, yet the grid layout seems to work fine so far. It almost seems like the `cell` value (provided via `grid.data.cell` in the calling functions) is accessed before it is refreshed correctly or something. I haven't yet fully grasped the implementation logic of the grid layout, maybe you can provide more insight here. I assume this proposed fix should be non-destructive?

**Comment by worron** [comment]
>I assume this proposed fix should be non-destructive?

Yes, it should be ok. But there is a bit different approach in my mind. I would be grateful if you will check commit mentioned above.

Also I should admit, `grid` layout code have some flaws in terms of multi screen support. Some glitches may appear when `grid` layout active on both screens. Just open another issue if you face something like that.

**Comment by worron** [comment]
>Awesome seems to restart itself automatically, as soon as the layout changes

Here some clarification should be. Normally (default config) `awesome` can handle monitor setup change without restart. This feature was introduced with 4.0 version. At that time `redflat` module already existed, and  significant part of code require rework to adopt new behavior. As single monitor user I want avoid this part of work and I've set signal to force `awesome` restart on screen changes. In `signals-config.lua` you can find line
```lua
screen.connect_signal("list", awesome.restart)
```
So you can delete this setting to try avoid WM restart. But in this case some `redflat` widgets (`layoutbox`, `taglist`, `tasklist` and possible custom layouts `grid` and `map`) can be pretty unstable. I don't recommend use mentioned widgets in non-restart mode. Hope for your understanding.

**Comment by M4he** [comment]
> Yes, it should be ok. But there is a bit different approach in my mind. I would be grateful if you will check commit mentioned above.

Checked out the commit. Worked just as fine so far. It's great to have solution to the root of the problem :) Will close this issue, thanks!

> At that time redflat module already existed, and significant part of code require rework to adopt new behavior. As single monitor user I want avoid this part of work and I've set signal to force awesome restart on screen changes.
> [...]
> So you can delete this setting to try avoid WM restart. But in this case some redflat widgets (layoutbox, taglist, tasklist and possible custom layouts grid and map) can be pretty unstable. I don't recommend use mentioned widgets in non-restart mode. Hope for your understanding.

Thanks for the clarification - completely reasonable, so no problem. You already did a fantastic job with `redflat` as is, kudos for that!
